### ISSUE TITLE
SyntaxError under Node 4.x

### ISSUE THREAD

**Issue by asnowfix** [kriasoft/node-sqlite#13]
Although I am using Promises, it seems that this module has strict requirements on Node 6.x, because it fails quickly when run on Node 4/x: 

```
./node_modules/sqlite/main.js:16
function prepareParams(args, { offset = 0, excludeLastArg = false } = {}) {
                             ^

SyntaxError: Unexpected token {
```

I would suggest to either set default parameter values using an ES5-compatible way (prefered, so that I can use it) or to state in the package.json that node-sqlite is strictly compatible with Node 6.x & beyond:

```
  "engineStrict" : true,
  "engines" : {
    "node" : ">=6"
   },
```

**Comment by pabigot** [comment]
I'm curious why this hasn't been addressed in the last three months.  I was looking for a promisified sqlite3 for node 4.x but trying it out it the tests won't even run because `tools/build.js` doesn't have `'use strict'`.  It's perfectly reasonable to require a "real" ES6 implementation but please at least note that requirement in the package.json and other documentation so people who have to use older LTS releases can look elsewhere for solutions.

**Comment by theogravity** [comment]
The readme does say

`NOTE: For Node.js v5 and below use var db = require('sqlite/legacy');.`

**Comment by theogravity** [comment]
Closing as 4.x is not used much nowadays
