### ISSUE TITLE
Getting multiple errors in React TypeScript

### ISSUE THREAD

**Issue by joki20** [kriasoft/node-sqlite#170]
**localhost:3000 (React)**
![image](https://user-images.githubusercontent.com/73738545/215598141-08cb0566-6712-47de-b4bd-afa44187e1f8.png)

**Terminal:**
![image](https://user-images.githubusercontent.com/73738545/215598282-80a1bb99-eac8-453b-a122-2c0d7443956a.png)

**App.tsx**
![image](https://user-images.githubusercontent.com/73738545/215598550-4e32b170-0258-4b2e-8bc0-abb681b270a6.png)

What is causing all these errors?

**Comment by theogravity** [comment]
You can't use `sqlite3` on the frontend side of things (assuming this is client-side rendered). 

Probably also further compounded by using cygwin (why not just use WSL)?

This isn't an issue specific to this library and you should ask in https://github.com/TryGhost/node-sqlite3 since the errors are coming from that library instead. This is just a wrapper around it.
