### ISSUE TITLE
Suggestion: tell about how Database#each is promisified

### ISSUE THREAD

**Issue by Hibou57** [kriasoft/node-sqlite#34]
The SQLite module documentation refers to the SQLite3 module documentation, which documents `Database#each`. After the definition of the latter, it's hard to guess how it is promisified in the SQLite module. It's rather mandatory to separately document this.

**Comment by theogravity** [comment]
Agreed and as always PRs are welcomed

**Comment by Astrydax** [comment]
Yeah, I got fed up with figure out/get this to work myself and just switched back to SQLite3

**Comment by Astrydax** [comment]
Credit Space from the Discord.js discord server. As he put it: "promises can only resolve once, you have to pass a callback for the 'each' part, the promise resolves after all rows have been run iirc" because of this, it's kinda impossible to circumvent callbacks without rewriting sqlite3 itself.

I would have to imagine the promise doesn't resolve until the loop has finished calling the supplied callback for each of the rows found by the query. 

`db.each(`SELECT * FROM table`, function(err, row) {
      if (err) console.log(err);
      console.log(row);
    }).then(function() {
      console.log("finished callbacks on each row");
    });`

**Comment by theogravity** [comment]
v4 now has this documented in the readme, thanks
